### ISSUE TITLE
 Error installing the CLI on windows

### ISSUE THREAD

**Issue by scorpioliu3** [oracle/oci-cli#108]
Hi 

when i install the CLI on windows according the document of Quickstart , the error appear.  What can i do?

iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/
install/install.ps1')) : Executing C:\Python37\python.exe C:\Users\scorpioliu\AppData\Local\Temp\tmpDC28.tmp returned a
 non-zero exit code.
所在位置 行:280 字符: 9
+         Write-Error "Executing $PythonExecutable $ArgumentList return ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

**Comment by rfennet** [comment]
Windows 10 PRO version: 10.0.17134. , Python 3.6.5 . Save behavior with Python 3.7.0.

Following instructions on https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliinstall.htm, it seems all commands need to be run from the elevated powershell. However, in my environment , downloading virtualenv package from https://github.com/pypa/virtualenv/archive/15.0.0.tar.gz times out .....

The timeout is caused by being behind a firewall, I do need to set https_proxy appropriately  for the download and subsequent install to finish. 

As far as I was able to find out, you cannot set https_proxy inside your powershell effectively, so I was able to make it work by:
- starting an elevated command prompt;
- set https_proxy=<your proxyhost>:<proxyport>;
- run the Windows, step 3 powershell command from within the elevated command window.

Anyone for a smarted solution ?

**Comment by paul-hummel-oracle** [comment]
@rfennet,
Thanks for the tips.

FYI, I use commands like this to set the proxy in powershell:
$Env:http_proxy="http://www.XXXXXXXX.com:80"
$Env:https_proxy="http://www.XXXXXXXX.com:80"
$Env:HTTP_PROXY="http://www.XXXXXXXX.com:80"
$Env:HTTPS_PROXY="http://www.XXXXXXXX.com:80"

**Comment by rfennet** [comment]
Duh ... thanks  Paul, that does the trick. I added only one https line into my PS $profile file (it turns out case does not matter), and then you can run the install command directly from the powershell too. Hope this helps others. BFN

**Comment by paul-hummel-oracle** [comment]
With the release of https://github.com/oracle/oci-cli/releases/tag/v2.4.42, we upgraded third party module versions for requests, cx_Oracle, pyOpenSSL, and cryptography. This should resolve many installation issues for Python 3.7 on Windows.
