### ISSUE TITLE
Is there anyway to list only Custom created Images rather than listing all the Images.

### ISSUE THREAD

**Issue by chowduri** [oracle/oci-cli#24]
We have Imported some of the Images from other tenancies, and as a requirement we need to list only those in "oci compute image list", Please let me know if that's possible.

**Comment by mross22** [comment]
On the service side we only make a distinction between system images and custom images. Custom images can be created via snapshot (from a running instance) or import (from object store). Custom images created from snapshot have operatingSystem set to the same OS as the instance. Imported images have the operatingSystem set to "Custom".

Because in your case it sounds like your images are imported, you could use the --operating-system parameter in the CLI to filter to only Custom imported images (for example --operating-system 'Custom'). Note that this will exclude images that are snapshots. There are still some decisions being made about how to distinguish between these two groups so this convention of operating-system == 'Custom' for imported images may change in the future.

Depending on how much control you have over the names of your imported images, you can also choose a consistent naming prefix and do client side filtering of the images using the --query parameter of the CLI. For example, if all of your custom image names begin with 'Imported' you could use the following command:

    oci compute image list -c $C_CLI --query 'data[?starts_with(@."display-name", `Imported`)]'

**Comment by et304383** [comment]
@mross22 hate to necro this thread, but 4 and a half years later, not having any kind of filtering server side for the image owner (OCI vs private) like AWS CLI has is disappointing.  Or supporting wildcards in the display name parameter like AWS CLI does.

Basically, you should just be doing what the AWS CLI does.  That's a good starting point.
