### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by brunoborges** [oracle/oci-cli#31]

**Comment by nathan-vu** [comment]
Assume that this is the same as per the comment here: https://github.com/oracle/oci-python-sdk/issues/39

So support either (or both)  [Wercker](https://app.wercker.com/Oracle/) or [Travis CI](https://travis-ci.org/oracle/). I can take a look

**Comment by nathan-vu** [comment]
Sorry for the delayed response. A wercker.yml file will be available in our next release (Thursday); this will contain three pipelines:

* build-py27
* build-py35
* build-py36

Corresponding to the Python major versions we support. These pipelines can be run in parallel (i.e. they are independent of each other don't need to be executed sequentially)

It looks like I don't have access to: https://app.wercker.com/Oracle/ so I can't do the configuration on that side.

**Comment by nathan-vu** [comment]
The wercker.yml file I mentioned in my previous comment has been deployed. Looks like I don't have access to do the configuration in Wercker - if I can be given access I'm happy to set it up on that end, otherwise I believe that pipelines can be set up using our YAML file (I validated it locally using the Wercker CLI)
