### ISSUE TITLE
Python 3.4 compatibility question on SUSE Linux Enterprise Server 12

### ISSUE THREAD

**Issue by glaubitz** [oracle/oci-cli#329]
Hello!

I'm currently packaging the Python OCI SDK and OCI CLI utility for the SUSE Linux Enterprise distributions 12 and 15.

While getting the OCI packages into SLE-15 showed did not cause any compatibility issues, the old version of the Python interpreter in SLE-12 does not seem to be supported.

Running the ```oci``` command on SLE-12, prints the following warning:

```suse_gce@sle-12-ocitest:~> oci
/usr/lib64/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
WARNING: OCI CLI now requires Python 3.5+. Please install or upgrade your version of Python to 3.5+ before February 13, 2020 to avoid interruption to CLI usage.
Usage: oci [OPTIONS] COMMAND [ARGS]...

  Oracle Cloud Infrastructure command line interface, with support for
  Audit, Block Volume, Compute, Database, IAM, Load Balancing, Networking,
  DNS, File Storage, Email Delivery and Object Storage Services.

  Most commands must specify a service, followed by a resource type and then
  an action. For example, to list users (where $T contains the OCID of the
  current tenant):

    oci iam user list --compartment-id $T

  Output is in JSON format.

  For information on configuration, see
  https://docs.cloud.oracle.com/Content/API/Concepts/sdkconfig.htm.
(...)
  session                Session commands for CLI
  setup                  Setup commands for CLI
  streaming              Streaming Service
  waas                   Web Application Acceleration and Security Services
  work-requests          Work Requests
suse_gce@sle-12-ocitest:~>
```

While the compatibility issue with OpenSSL is something we can address in SLE-12 by updating to a newer version of OpenSSL via our maintenance mechanisms, updating to a newer major version of the Python interpreter is nearly impossible as the risk is too high of breaking too many unrelated packages.

So, my question is what are the reasons for deprecating support for Python 3.4 and is there any chance that OCI CLI will remain usable in the future with SLE-12 which is what we have on SLE-12?

It would be a pity if we couldn't ship Python OCI SDK and the OCI CLI utility with SLE-12 as we actually want to provide the SDKs and CLI packages of all the common public cloud vendors on our enterprise products.

**Comment by kernleee** [comment]
Hi @glaubitz, we have never supported Python <3.5 versions as long as I remember. We currently support Python 2.7+, with future plans of deprecating Python 2, and Python 3.5+. 
In terms of the error message, newer versions will not have that error message. We've removed that message because we thought it was slightly confusing.

You can find a list of our supported Python versions here https://docs.cloud.oracle.com/en-us/iaas/Content/API/Concepts/cliconcepts.htm#Requirements
We will not be supporting Python <3.5, but the CLI can still possibly still work on those versions. We just won't be fixing issues or running tests to verify usage on Python <3.5.

I'll be closing this for now. If you have more questions, please feel free to reopen this.
Thank you!
