### ISSUE TITLE
miss match between data in web console and oci search resource structured-search

### ISSUE THREAD

**Issue by djivide** [oracle/oci-cli#371]
We have noticed a few times now where the data being reported by the console does not match up with the data returned from oci search resource structured-search --query-text. We use the cli query to search for any resources we may have left running and as such getting false alerts when the structured-search falsely reports resources as running when they have in fact been terminated correctly via terraform.

The query we run is the following for a number of users : 
oci search resource structured-search --query-text  "query instance resources where lifeCycleState != 'TERMINATED'"  && (definedTags.namespace = 'Operations' && definedTags.key = 'CreateBy' && ($Utagmatch) )

This is not really reproducible, we have hit the issue three or four times in the past six months, while the data usually does sync up in a couple of hours we have seen cases were the data was out of sync for up to day when it happened over the weekend once.

**Comment by KartikShrikantHegde** [comment]
Hi @djivide , Have you faced the issue recently again?

the RQS service team thinks it will be difficult to triage this issue without being able to reproduce it. Ideally, both, the console and the CLI hit the same endpoint and they should not have any difference. As you rightly suggested search is eventually consistent. If you have hit the error please report the issue so that we can investigate. Please do provide the opc-request-id.

**Comment by KartikShrikantHegde** [comment]
Hi @djivide , please re-open the issue if you hit the error again. I will close the issue for now.
