### ISSUE TITLE
--generate-full-command-json-input command doesn't include all required fields

### ISSUE THREAD

**Issue by jasonyin** [oracle/oci-cli#38]
the json generated here:
xxx-mac~/Documents % oci db system launch --generate-full-command-json-input         
{
  "adminPassword": "string", 
  "availabilityDomain": "string", 
  "backupSubnetId": "string", 
  "characterSet": "string", 
  "clusterName": "string", 
  "compartmentId": "string", 
  "cpuCoreCount": 0, 
  "dataStoragePercentage": 0, 
  "databaseEdition": "STANDARD_EDITION|ENTERPRISE_EDITION|ENTERPRISE_EDITION_EXTREME_PERFORMANCE|ENTERPRISE_EDITION_HIGH_PERFORMANCE", 
  "dbName": "string", 
  "dbVersion": "string", 
  "dbWorkload": "string", 
  "diskRedundancy": "HIGH|NORMAL", 
  "displayName": "string", 
  "domain": "string", 
  "hostname": "string", 
  "initialDataStorageSizeInGb": 0, 
  "licenseModel": "LICENSE_INCLUDED|BRING_YOUR_OWN_LICENSE", 
  "maxWaitSeconds": 0, 
  "ncharacterSet": "string", 
  "nodeCount": 0, 
  "pdbName": "string", 
  "shape": "string", 
  "subnetId": "string", 
  "waitForState": "PROVISIONING|AVAILABLE|UPDATING|TERMINATING|TERMINATED|FAILED", 
  "waitIntervalSeconds": 0
}

from the service api, the sshpublickeys is required, but not generated
https://docs.us-phoenix-1.oraclecloud.com/api/#/en/database/20160918/DbSystem/LaunchDbSystem 

one more question:
I saw there is a parameter '--ssh-authorized-keys-file' which is different than the service spec, is it expected?

**Comment by nathan-vu** [comment]
This is intentional - not every CLI operation is 1:1 with an operation in the REST API, so you shouldn't try and marry up the fields like you're trying to do here (admittedly, you'd probably get the right information > 90% of the time, though)

In this case, we do not have a parameter corresponding to the `sshPublicKeys` field that you see in the API documentation because this would be surfaced in the CLI as asking customers to provide a string array, which is ungainly. Instead, we ask customers to pass in this information via `ssh-authorized-keys-file` (with one key per line if a customer needs to pass in multiple keys). Internally, when the CLI calls the `LaunchDbSystem` operation it will translate this into the `sshPublicKeys` field which that operation expects to receive.

That being said, in the JSON it looks like we aren't showing fields for file-type parameters. This needs to be fixed.

**Comment by nathan-vu** [comment]
The issue with not showing fields for file-type parameters has been fixed in the latest CLI release

```
>> oci --version
2.4.16

>> oci db system launch --generate-full-command-json-input
{
  "ad": "string",
  "adminPassword": "string",
  "availabilityDomain": "string",
  "backupSubnetId": "string",
  "characterSet": "string",
  "clusterName": "string",
  "compartmentId": "string",
  "cpuCoreCount": 0,
  "dataStoragePercentage": 0,
  "databaseEdition": "STANDARD_EDITION|ENTERPRISE_EDITION|ENTERPRISE_EDITION_EXTREME_PERFORMANCE|ENTERPRISE_EDITION_HIGH_PERFORMANCE",
  "dbName": "string",
  "dbVersion": "string",
  "dbWorkload": "string",
  "diskRedundancy": "HIGH|NORMAL",
  "displayName": "string",
  "dn": "string",
  "domain": "string",
  "hostname": "string",
  "initialDataStorageSizeInGb": 0,
  "licenseModel": "LICENSE_INCLUDED|BRING_YOUR_OWN_LICENSE",
  "maxWaitSeconds": 0,
  "ncharacterSet": "string",
  "nodeCount": 0,
  "pdbName": "string",
  "shape": "string",
  "sshAuthorizedKeysFile": "/path/to/file",
  "subnetId": "string",
  "waitForState": "PROVISIONING|AVAILABLE|UPDATING|TERMINATING|TERMINATED|FAILED",
  "waitIntervalSeconds": 0
}
```

Note the presence of the `sshAuthorizedKeysFile` field, where a customer should specify the path to the file the command should use for this parameter.
