### ISSUE TITLE
SecurityProtocol issue in Powershell 7

### ISSUE THREAD

**Issue by davidkhala** [oracle/oci-cli#380]
I find out that our `install.ps1` does not work on Powershell 7 and prompt error like 
```
Exception setting "SecurityProtocol": "The requested security protocol is not supported."
 ```
This error does not exist on Windows Powershell (5.1)

**Comment by davidkhala** [comment]
@vish1 If you have no resource for it, I am glad to be assignee

**Comment by Jawz84** [comment]
Hi, I have looked into this, and found the problem. Since I have no signed OCA, I cannot offer a PR at this point, but this is very easily fixed.

These are the relevant lines of code from `install.ps1`:

```powershell
# Explicitly support TLS 1.2 only if OS supports it
if ([System.Enum]::GetNames('System.Net.SecurityProtocolType') -Contains 'Tls12') {
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12';
}
```

To fix the issue, you need to change `[System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12';` to `[System.Net.SecurityProtocolType]::Tls12;`.

In pwsh, there is improved error handling for this, that is why there is an error in pwsh. In powershell.exe, this was also broken, but silently so. To see for yourself that this was in fact broken in powershell.exe as well, you can test with `([System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12').value__`. It will error out, saying that it cannot convert to one of the enum values available.

Kind regads of a passerby who is trying to help out :)

**Comment by davidkhala** [comment]
@Jawz84 Jos, Thanks so much for your hints! You deserve an special acknowlegement section for its PR. 👍
