### ISSUE TITLE
oci cli route table list jmespath query bug

### ISSUE THREAD

**Issue by luckeyca** [oracle/oci-cli#609]
oci cli route table list jmespath query returns more value than it should.

steps to reproduce.

1. create a test vcn called test-vcn
2. create a test route table inside the test-vcn called test-ig-route-table(display name)
3. run the oci route table list command with jmespath query filter by displayName to get the ocid, the result returns both the test route table and the vcn default route tables ocids as below.

oci network route-table list --region ca-toronto-1 --compartment-id "ocid1.compartment.oc1..aaaaaaaahoxwegjsy4suya6dordeulj3njjv2tx5bjvvoibkhm2p2h5cmp6a" --query 'data[?displayName=="test-ig-route-table"].id'

5. run the  oci search resource structured-search command using the same filter returns the one single correct ocid 

oci search resource structured-search --region ca-toronto-1 --query-text "QUERY routetable resources where lifeCycleState == 'AVAILABLE' && displayName == 'test-ig-route-table'"

**Comment by mandyht** [comment]
--query is quite picky with the quotes you use. A few points to pay attention to:
* ``displayName`` should be ``display-name``. Because there's a dash in this key, you'll need quotes around it.
* Since displayName is not recognized, it is giving you all route tables found.
* Whenever you have a condition in your query, make sure your value is wrapped in **single** quotes.

Your command should be:
``oci network route-table list --compartment-id $ocid --query "data[?\"display-name\"=='test-ig-route-table'].id" ``

Please let me know if you're still getting an unexpected output.
