### ISSUE TITLE
lint issue: oci cli query values have trailing whitespace

### ISSUE THREAD

**Issue by luckeyca** [oracle/oci-cli#610]
some of the oci query value has trailing whitespace which makes it more time consuming and difficult to troubleshoot and parse.

for example

vcn_parent_compartment_ocid = $(oci search resource structured-search --region ca-toronto-1 --query-text "QUERY vcn resources where lifeCycleState == 'AVAILABLE' && cidrBlocks == '192.168.1.0/24'" --query 'data.items[0]."compartment-id"')

This value has a trailing newline "\n" key which makes the following command returns with error

oci network route-table list --region ca-toronto-1 --compartment-id #vcn_parent_compartment_ocid} --vcn-id

**Comment by luckeyca** [comment]
please do proper lint check to make sure no trailing whitespace anywhere.

**Comment by karthik-k-kamath** [comment]
Thanks Cheng Lu, for highlighting this.
We shall investigate and get back here.

**Comment by pankajmjx** [comment]
The above command is failing because the result of first query is returned with double quotes("").These double quotes are getting used as character when used in second query. Making change to CLI code is not feasible for this so you can strip these quotes to use this variable in second query so that the command can work without any error.

**Comment by pankajmjx** [comment]
Closing the issue due to above reason.Please feel free to reopen the issue if further help is required from CLI team.
