### ISSUE TITLE
Not able to access buckets/objects from OCI CLI

### ISSUE THREAD

**Issue by kjoshi07** [oracle/oci-cli#68]
I have properly seted up OCI at my instance and trying to access buckets/objects from command line but getting NotAuthenticatederror:

 #oci os object list -ns *******-bn ************
ServiceError:
{
    "code": "NotAuthenticated",
    "message": "The required information to complete authentication was not provided.",
    "opc-request-id": "651A4773BFD745919585A7FC2E4CBC00",
    "status": 401
}

**Comment by nathan-vu** [comment]
Hi,

A couple of things to check:

* For belt and suspenders, confirm that there is clock skew: https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/usingapi.htm#Maximum (I suspect you aren't getting this as otherwise the CLI would print you a warning message)
* Do you have a complete config file at `~/.oci/config` with user, tenancy, fingerprint information etc.
* Is the fingerprint in your configuration file associated with an API Key your OCI user (you should be able to check this by viewing the user's record in the OCI console)
* Does this happen on all commands or just listing buckets? (e.g. if you run `oci os ns get` does that succeed and print out your Object Storage namespace)
  * An associated question is does your user have permission to list objects on the bucket?

**Comment by kjoshi07** [comment]
Point 1: Yes bucket exist.
Point 2: I have created a policy with Allow group ********** to manage buckets in tenancy
then assign that user to that Group.
Point 3: oci os ns get give me correct name space and I can also see name on bucket detail they match.

**Comment by nathan-vu** [comment]
re: the policy you created, did you only give the group permission to manage buckets? If so, then you also need to grant the group permission to manage objects. 

Referring to [this](https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Reference/objectstoragepolicyreference.htm) page, the permission to list objects is independent of the permissions around managing buckets. Specifically, you should note on that page that managing buckets does not give permission to the `ListObjects` operation (which is what `oci os object list` uses because that CLI commands lists objects in a bucket)

**Comment by kjoshi07** [comment]
thank you so much @nathan-vu , I just given permission to manage objects and now I can access bucket.

thanks a ton.
KJ

**Comment by nathan-vu** [comment]
No worries - glad to hear that it's working now

**Comment by keyurdgp** [comment]
I am getting following error for most of the command but when I do _**oci os ns get**_ It works fine. Any idea what i am running into this problem. 

% oci compute image list --compartment-id $cid
ServiceError:
{
    "code": "NotAuthorizedOrNotFound",
    "message": "Authorization failed or requested resource not found.",
    "opc-request-id": "B828D69BBBC843DABCFA2EBBEC8C4C72/55AA0A890611613F8CF11855E57EE6FD/1F2B1BA0AA7914984B4D000E14EF54BA",
    "status": 404
}


keyurpatel@keyurpatel-mac .oci % oci os ns get
{
  "data": "myoci04"
}
keyurpatel@keyurpatel-mac .oci %

**Comment by vish1** [comment]
@keyurdgp Please do not comment on closed issues. Please open a new one if you have an issue. In this case, please confirm that you have the required policy/permissions to execute the compute image list command.
