### ISSUE TITLE
can not get a string value using --raw-output

### ISSUE THREAD

**Issue by rywatabe** [oracle/oci-cli#77]
hi, experts

can not get a string value using --raw-output

expected result is ...
```
$ oci network vcn list --query 'data[?"display-name"==`'${VCN_NAME}'`].id' --raw-output
ocid1.vcn.oc1.iad.aaaaaaaa....
```
but, actual result is ...

```
$ oci network vcn list --query 'data[?"display-name"==`'${VCN_NAME}'`].id' --raw-output
[
  "ocid1.vcn.oc1.iad.aaaaaaaa...."
]
$ oci network vcn list --query 'data[?"display-name"==`'${VCN_NAME}'`].id' --raw-output --output=table
+--------------------------------------------------------------------------------+
| Column1                                                                        |
+--------------------------------------------------------------------------------+
| ocid1.vcn.oc1.iad.aaaaaaa... |
+--------------------------------------------------------------------------------+
$ oci --version
2.4.29
```

thanks!

**Comment by paul-hummel-oracle** [comment]
HI, because this is returning a list, we will have to reduce it to a single element first.
Please try the pipe operator and specify the first index in the list.  
For example:

oci network vcn list --compartment-id ocid1.compartment.oc1....... --query 'data[?"display-name"==`'${VCN_NAME}'`].id **| [0]**' --raw-output

**Comment by rywatabe** [comment]
I understood I have to do "unwrap" operation in order to get what I need. 
Thanks :-)
